name = "anniversary-site"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "."

[vars]
NODE_VERSION = "20"